# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f86de282c9cd279fe05e7fe692374b7a44b64ac5f551debf13f7021c87e042fa4c4fec9e43d33a2e9bdcde3541817d41a5920f40afed3ad1bf0e7695bb0e341

test:
  secret_key_base: 872c8b07d9fc73c9054fd824f379c0a938680913e85b4262165cc240a1770edca1a45bac55b8b06477cbf2b500b6de2d3694f787aa009e91f10b69dd00adb82c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
